//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Postamat3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Посылка.
    /// </summary>
    // *** Start programmer edit section *** (Посылка CustomAttributes)

    // *** End programmer edit section *** (Посылка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПосылкаE", new string[] {
            "Номер as \'Номер\'",
            "Статус as \'Статус\'",
            "Отправитель as \'Отправитель\'",
            "Получатель as \'Получатель\'",
            "Логистика as \'Логистика\'",
            "Логистика.Информация as \'Информация\'",
            "Транзакция as \'Транзакция\'",
            "Транзакция.Время as \'Время\'"}, Hidden=new string[] {
            "Логистика.Информация",
            "Транзакция.Время"})]
    [MasterViewDefineAttribute("ПосылкаE", "Логистика", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Информация")]
    [MasterViewDefineAttribute("ПосылкаE", "Транзакция", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Время")]
    public class Посылка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Postamat3.Статусы fСтатус;
        
        private string fОтправитель;
        
        private string fПолучатель;
        
        private IIS.Postamat3.Логистика fЛогистика;
        
        private IIS.Postamat3.Транзакция fТранзакция;
        
        private IIS.Postamat3.Ячейка fЯчейка;
        
        // *** Start programmer edit section *** (Посылка CustomMembers)

        // *** End programmer edit section *** (Посылка CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Номер CustomAttributes)

        // *** End programmer edit section *** (Посылка.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Номер Get start)

                // *** End programmer edit section *** (Посылка.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Посылка.Номер Get end)

                // *** End programmer edit section *** (Посылка.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Номер Set start)

                // *** End programmer edit section *** (Посылка.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Посылка.Номер Set end)

                // *** End programmer edit section *** (Посылка.Номер Set end)
            }
        }
        
        /// <summary>
        /// Отправитель.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Отправитель CustomAttributes)

        // *** End programmer edit section *** (Посылка.Отправитель CustomAttributes)
        [StrLen(255)]
        public virtual string Отправитель
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Отправитель Get start)

                // *** End programmer edit section *** (Посылка.Отправитель Get start)
                string result = this.fОтправитель;
                // *** Start programmer edit section *** (Посылка.Отправитель Get end)

                // *** End programmer edit section *** (Посылка.Отправитель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Отправитель Set start)

                // *** End programmer edit section *** (Посылка.Отправитель Set start)
                this.fОтправитель = value;
                // *** Start programmer edit section *** (Посылка.Отправитель Set end)

                // *** End programmer edit section *** (Посылка.Отправитель Set end)
            }
        }
        
        /// <summary>
        /// Получатель.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Получатель CustomAttributes)

        // *** End programmer edit section *** (Посылка.Получатель CustomAttributes)
        [StrLen(255)]
        public virtual string Получатель
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Получатель Get start)

                // *** End programmer edit section *** (Посылка.Получатель Get start)
                string result = this.fПолучатель;
                // *** Start programmer edit section *** (Посылка.Получатель Get end)

                // *** End programmer edit section *** (Посылка.Получатель Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Получатель Set start)

                // *** End programmer edit section *** (Посылка.Получатель Set start)
                this.fПолучатель = value;
                // *** Start programmer edit section *** (Посылка.Получатель Set end)

                // *** End programmer edit section *** (Посылка.Получатель Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Статус CustomAttributes)

        // *** End programmer edit section *** (Посылка.Статус CustomAttributes)
        public virtual IIS.Postamat3.Статусы Статус
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Статус Get start)

                // *** End programmer edit section *** (Посылка.Статус Get start)
                IIS.Postamat3.Статусы result = this.fСтатус;
                // *** Start programmer edit section *** (Посылка.Статус Get end)

                // *** End programmer edit section *** (Посылка.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Статус Set start)

                // *** End programmer edit section *** (Посылка.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Посылка.Статус Set end)

                // *** End programmer edit section *** (Посылка.Статус Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Логистика CustomAttributes)

        // *** End programmer edit section *** (Посылка.Логистика CustomAttributes)
        [PropertyStorage(new string[] {
                "Логистика"})]
        [NotNull()]
        public virtual IIS.Postamat3.Логистика Логистика
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Логистика Get start)

                // *** End programmer edit section *** (Посылка.Логистика Get start)
                IIS.Postamat3.Логистика result = this.fЛогистика;
                // *** Start programmer edit section *** (Посылка.Логистика Get end)

                // *** End programmer edit section *** (Посылка.Логистика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Логистика Set start)

                // *** End programmer edit section *** (Посылка.Логистика Set start)
                this.fЛогистика = value;
                // *** Start programmer edit section *** (Посылка.Логистика Set end)

                // *** End programmer edit section *** (Посылка.Логистика Set end)
            }
        }
        
        /// <summary>
        /// Посылка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Транзакция CustomAttributes)

        // *** End programmer edit section *** (Посылка.Транзакция CustomAttributes)
        [PropertyStorage(new string[] {
                "Транзакция"})]
        [NotNull()]
        public virtual IIS.Postamat3.Транзакция Транзакция
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Транзакция Get start)

                // *** End programmer edit section *** (Посылка.Транзакция Get start)
                IIS.Postamat3.Транзакция result = this.fТранзакция;
                // *** Start programmer edit section *** (Посылка.Транзакция Get end)

                // *** End programmer edit section *** (Посылка.Транзакция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Транзакция Set start)

                // *** End programmer edit section *** (Посылка.Транзакция Set start)
                this.fТранзакция = value;
                // *** Start programmer edit section *** (Посылка.Транзакция Set end)

                // *** End programmer edit section *** (Посылка.Транзакция Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Postamat3.Ячейка.
        /// </summary>
        // *** Start programmer edit section *** (Посылка.Ячейка CustomAttributes)

        // *** End programmer edit section *** (Посылка.Ячейка CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Ячейка"})]
        public virtual IIS.Postamat3.Ячейка Ячейка
        {
            get
            {
                // *** Start programmer edit section *** (Посылка.Ячейка Get start)

                // *** End programmer edit section *** (Посылка.Ячейка Get start)
                IIS.Postamat3.Ячейка result = this.fЯчейка;
                // *** Start programmer edit section *** (Посылка.Ячейка Get end)

                // *** End programmer edit section *** (Посылка.Ячейка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Посылка.Ячейка Set start)

                // *** End programmer edit section *** (Посылка.Ячейка Set start)
                this.fЯчейка = value;
                // *** Start programmer edit section *** (Посылка.Ячейка Set end)

                // *** End programmer edit section *** (Посылка.Ячейка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПосылкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосылкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосылкаE", typeof(IIS.Postamat3.Посылка));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Посылка.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПосылка CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПосылка CustomAttributes)
    public class DetailArrayOfПосылка : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Postamat3.DetailArrayOfПосылка members)

        // *** End programmer edit section *** (IIS.Postamat3.DetailArrayOfПосылка members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Посылка by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Посылка.
        /// </summary>
        public DetailArrayOfПосылка(IIS.Postamat3.Ячейка fЯчейка) : 
                base(typeof(Посылка), ((ICSSoft.STORMNET.DataObject)(fЯчейка)))
        {
        }
        
        public IIS.Postamat3.Посылка this[int index]
        {
            get
            {
                return ((IIS.Postamat3.Посылка)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Postamat3.Посылка dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
